Repository ProgramEquity/amplify, pull requests merged in 2023-12, with the labels that each got.

#800 [Documentation] Update ReadMe graphics to reference Cicero API #651
  README.md
Labels: ✍️ documentation, new contributor

#851 refactor lob api tests to be more readable with inline comments
  .github/workflows/finish-hackpod.yml
  roiScript/send-metrics.mjs
  server/__tests__/integration/lob.test.js
Labels: new contributor

#864 issue-863
  .github/workflows/finish-hackpod.yml
  roiScript/send-metrics.mjs
Labels: completed hackpod issue

#866 Add Twilio info for .env.example and CONTRIBUTING.MD
  .env.example
  CONTRIBUTING.md
  roiScript/send-metrics.mjs
Labels: new contributor

#701 Create new v1 Campaign PUT Rest Endpoint
  server/__tests__/integration/server/routes/api/v1/campaigns/campaign_put_endpoint.test.js
  server/api.js
  server/db/models/campaign.js
  server/routes/api/v1/campaigns/index.js
  server/routes/api/v1/v1.js
Labels: ⚙️ Back-end
