Repository ProgramEquity/amplify, pull requests merged in 2023-04, with the labels that each got.

#523 407 custom donation input 2
  server/routes/api/checkout.js
  src/components/DonateMoney.vue
  util/format.js
  util/validate.js
Labels: front-end

#551 Create Unit Tests GitHub Action Workflow
  .github/workflows/unit-tests.yml
Labels: 🏗 architecture, oss workflows, test

#522 Updating the Campaign Model
  server/db/migrations/20230309195953_update-campaign-model.js
  server/db/models/campaign.js
Labels: ⚙️ Dev
